- Source/Info-OSX.plist
- SwiftyJSON.xcodeproj/project.pbxproj
- SwiftyJSON.xcodeproj/xcshareddata/xcschemes/SwiftyJSON OSX.xcscheme
- SwiftyJSON.xcodeproj/xcshareddata/xcschemes/SwiftyJSON iOS.xcscheme
It's look like SwiftyJSON for OS X is not building correctly when using Carthage. So I modify the scheme of the OS X a little bit. Now I can run carthage and build SwiftyJSON for OS X.
Cheers.
> Fixed the broken Carthage OS X Support.

- Source/SwiftyJSON.swift
In my project I found the extension of JSON type with Swift protocol "SequenceType", to conflict with a type using the same name in another library (named FlipView). This pull request just fix this and other potential type conflict prefixing the extension with the Swift module.
> Prefixed "SequenceType" extension with Module name

- SwiftyJSON.xcodeproj/project.pbxproj
In order to properly support Carthage and CocoaPods at the same time with cross-platform targets, the code signing identities need to be modified a bit to make sure everyone can build SwiftyJSON using Carthage.
To properly support Carthage, iOS targets and tests need to code sign as `iPhone Developer`. This is due to the fact that Xcode *requires* them to be code signed. Thankfully, SwiftyJSON already has all of this set properly. Mac OS X targets and tests are different altogether. They don't require code signing at all. Therefore, it should be disabled to allow users without a `Mac Developer` account to build SwiftyJSON on OS X and run the tests. All frameworks will get resigned anyways when embedded within the final app target.
This will make creating cross-platform libraries ontop of …
> Updated code signing identities for OSX target and tests

- SwiftyJSON.xcodeproj/xcshareddata/xcschemes/SwiftyJSON OSX.xcscheme
Just by opening the project, Xcode is modifying the buildable name in the OS X scheme. My guess is that when the OS X target was created along with the scheme, the scheme just didn't get updated properly when the `Product Name` of the target was updated. This small change fixes up the issue.
> Fixed the buildable name in the OSX scheme

- README.md
- Use Swift 1.2 syntax: multiple if-let clauses
- Use Swift objects, that is `[String; AnyObject]` instead of `NSDictionary`
- In the second example, cast the final result to String
- Don't use `NSJSONReadingOptions.MutableContainers`, it does make the example look more awful than it is, but it is rarely needed...
> Update the first two examples snippets

- Source/SwiftyJSON.swift
Using arrayValue/dictionaryValue to get count is not efficient, just use object instead.
> Optimize performance of count

- Example/ViewController.swift
The order of  elements of   two array
"self.json.dictionaryValue.keys.array"   and  "(self.json.object as!
NSDictionary).allKeys"  is  different  , so  it  causes a  bug  in
appearance   i  turn them into the same one
> Example target  bug  fix

- Source/SwiftyJSON.swift
Fixes a crash when a parse error occurs, but no NSErrorPointer has been passed into the JSON initialiser.
> Fix bad memory access with optional error pointer

- Source/SwiftyJSON.swift
fixes compiler warning and uses NSCharacterSet.URLQueryAllowedCharacterSet() as allowedCharacters
> Fixes Compiler Warning for Xcode7B5

- Source/SwiftyJSON.swift
```
stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding)
```
The above is deprecated as of Xcode 7/Swift 2.0
This is Apple's recommended replacement:
```
stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.alphanumericCharacterSet())
```
> Update Deprecated Function

- Source/SwiftyJSON.swift
- Tests/BaseTests.swift
- Tests/NumberTests.swift
Code should never use floating point numbers to represent money, or any other value where exact decimal rounding is important. (See [here](http://spin.atomicobject.com/2014/08/14/currency-rounding-errors/) and [here](http://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency) for the reasons why.)
Because of this, developers often use strings to represent currency in JSON. However, SwiftyJSON’s `numberValue` applied to a string element parses the string as a double, thus defeating this technique. Because `numberValue` returns `NSNumber` and not `Double`, it’s not at all obvious to someone using SwiftyJSON that this floating point conversion happens — a potential source of dangerous bugs!
Cocoa provides `NSDecimalNumber` for exactly this situation, and …
> Parse string numbers as NSDecimalNumber instead of double

- Source/SwiftyJSON.swift
- Tests/BaseTests.swift
- Tests/RawTests.swift
The set of commits are as follows:
1. This accommodates a Foundation change in XCode 7 GM (`NSNumber` now conforms to `Swift.Comparable` by default)
2. XCTest > and < assertions care more about types, so this fixes the test in BaseTests that broke
3. The third commit fixes the way exceptions are handled in `rawData`. `testInvalidJSONForRawData` demonstrates the use case. Prior to the change, this test will fail, but it is never caught as `NSJSONSerialization` throws a different exception. Apple recommends validating the input with `isValidJSONObject` so I've added this to `rawData()` within a Swift 2.0 `guard`
> Fixes for issues found in Xcode 7 GM and error handling for rawData()

- SwiftyJSON.xcodeproj/project.pbxproj
This should fix #355 by adding `BITCODE_GENERATION_MODE` build settings to the watchOS and iOS targets. See [this issue](https://github.com/Carthage/Carthage/issues/535) for more info.
> Added Carthage bitcode support

- README.md
More appropriate to use 'index' as a variable name for an array
> Change key to index for array

- Source/SwiftyJSON.swift
[https://github.com/SwiftyJSON/SwiftyJSON/issues/375](https://github.com/SwiftyJSON/SwiftyJSON/issues/375)
So that we can use `enum` as keys like this:
```swift
enum J : String {
case Id = "id"
case ChannelId = "channel_id"
case ChannelTitle = "channel_title"
case Title = "title"
case Template = "template"
case Articles = "articles"
}
extensions J : JSONSubscriptType {
var jsonKey:JSONSubscriptKey {
return JSONSubscriptKey.Key(self.rawValue)
}
}
```
And use it like this
```swift
let idNumber = j[J.ChannelId].number ?? j[J.Id].number ?? NSNumber(int: 0)
```
> Adding Support for Custom JSONSubscriptType

- Source/Info-tvOS.plist
arm64 must be set in UIRequiredDeviceCapabilities for tvOS targets when uploading to iTunes Connect.
> Sets UIRequiredDeviceCapabilities for tvOS target

- Source/SwiftyJSON.swift
Wrong JSON's type specification URL, it should be http://www.json.org.
> Correct JSON's type specification URL

- SwiftyJSON.xcodeproj/project.pbxproj
Hi there,
I deleted the Framework search paths for target OSX Test - otherwise I get a warning during build (e.g. using carthage). The other targets are fine.
> Deleted Framework search paths for target OSX Test

- Source/SwiftyJSON.swift
- Tests/BaseTests.swift
So we don't contaminate public equal operator as referenced [here](https://github.com/SwiftyJSON/SwiftyJSON/issues/302)
> Keep NSNumber Operator Internal

- SwiftyJSON.xcodeproj/project.pbxproj
This pull request updates the code sign identity so that `carthage update --platform iOS` won't fail on travis ci.
> Update codesign identity

- SwiftyJSON.xcodeproj/project.pbxproj
was set to use always the most current watch OS version (currently 2.1) with the result that the lib is not usable with apps deploying on watchOS 2.0
> set the watch os deployment target to watchOS 2.0

- Source/SwiftyJSON.swift
- Tests/SequenceTypeTests.swift
The increment (++) and decrement (--) operators will be deprecated with Swift 3.
For more information, see proposal SE-0004: https://github.com/apple/swift-evolution/blob/master/proposals/0004-remove-pre-post-inc-decrement.md
> Replace ++ with +=

- Source/SwiftyJSON.swift
- Tests/BaseTests.swift
`isExists()` isn't the correct way to phrase that statement and makes the code harder to read. Simply using `exists()` makes it easer to read and grammatically correct.
```swift
json["user"].exists()
```
> Rename isExists to exists. Fixes #448

- Source/SwiftyJSON.swift
- `which's` doesnot seem to make lot of sense so i think its better off by using `whose`
- there was no space between `structuresby` which is changed to `structures by`
> Which's -> whose and typo fix in comments

- Source/SwiftyJSON.swift
The comment had array.empty which but it was implemented by array.isEmpty and similar for dictionary. Although the intent is clear, the comment suggested it was the code portion and it was mismatching. Thus, i think its necessary.
> Changed from .empty to .isEmpty

- Source/SwiftyJSON.swift
Referencing #633 , this PR updates the initialiser use of NSErrorPointer.
In Swift 3 `NSErrorPointer` is defined as:
`public typealias NSErrorPointer = AutoreleasingUnsafeMutablePointer<NSError?>?`
hence the optionality of the error parameter can be removed.
> Update NSErrorPointer usage in initializer.

- Source/SwiftyJSON.swift
This PR includes a fix that I think is required to correctly check two JSONIndex instances whose internal types are .null for equality. Without this fix, two .null JSONIndexes are considered not equal, which leads to problems when iterating over JSON objects. 
Lets say we have the following code:
```swift
for (index, subJson) in json["key_that_does_not_exists"] {
// other code
}
```
This leads to an infinite loop because the return values of startIndex, endIndex and index(after:) in the JSON: Collection extension all return .null Indexes which are considered not equal.
> fixed equality checking for JSONIndex

- README.md
seems to be, that the Swift Package Manager has updated the kind of defining Versions.
But on "swift build -v" we have still a issue:
/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swiftc --driver-mode=swift -I /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib/swift/pm -L /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib/swift/pm -lPackageDescription -target x86_64-apple-macosx10.10 /Users/jan/Development/iOS/Global\ Nights/Package.swift -fileno 4
/Users/jan/Development/iOS/Global Nights/Package.swift:15:17: error: incorrect argument labels in call (have 'url:tag:versions:', expected 'url:majorVersion:minor:')
.Package(url: "https://github.com/SwiftyJSON/SwiftyJSON.git", tag: "2.3.3", versions: Version(1,0,0)..<Version(2,3,3)),
^ …
> updated "Swift Package Manager" installation manual

- README.md
This pull request correctly changes the spelling of "Existance" to "Existence"
Additional reference: http://www.yourdictionary.com/existance
> correct README typo

- Source/SwiftyJSON.swift
- Tests/BaseTests.swift
- Tests/StringTests.swift
With Swift 3, the NS prefix is dropped from several Foundation classes, including `NSURL`, to avoid casting between classes SwiftyJSON should use `URL` instead as this is the default class in Swift 3 now.
> Swift 3: Move from NSURL to URL #649

- Source/SwiftyJSON.swift
- Tests/BaseTests.swift
Allow the `exists` method to handle out of bounds and wrong type errors by checking for `errorValue.code == ErrorIndexOutOfBounds` and `errorValue.code == ErrorWrongType`.
For example, when we have `let jsonForArray = JSON([["number":1111]])` we would expect `jsonForArray[1].exists()` and `jsonForArray["someValue"].exists()` to return false.
I think the change here might fix the issue related to https://github.com/SwiftyJSON/SwiftyJSON/issues/498
> Allow exists method to handle out of bounds and wrong type errors

- Source/SwiftyJSON.swift
- Tests/BaseTests.swift
- Tests/ComparableTests.swift
- Tests/LiteralConvertibleTests.swift
- Tests/PrintableTests.swift
- Tests/RawTests.swift
- Tests/SubscriptTests.swift
First step to remove adoption of `NilLiteralConvertible`
https://github.com/SwiftyJSON/SwiftyJSON/issues/670
Thanks to @Igor-Palaguta
> Remove nil convertable

- Example/Example/Base.lproj/Main.storyboard
- Example/Example/ViewController.swift
The previous segue is pointed to the navigation controller. This causes the show segue to be presented instead on the current navigation controller. Attaching the segue to the view controller itself.
> Fix issue #603 Improve example with push segue

- Source/SwiftyJSON.swift
- Tests/StringTests.swift
Before the Swift 3 update, boolValue used the NSString boolvalue
property. This property would return true for 'Y','y','T','t' in
addition to 'true'.
See more at:
https://developer.apple.com/reference/foundation/nsstring/1409420-boolvalue
Change Introduced in:
cf657820fad3656df022d8ebf32f9cdd99e1247a
During the swift 3 upgrade, this was changed slightly so only "true"
would return true. This commit updates that behavior to match the
previous behavior for projects relying on that functionality.
> Match pre-swift3 behavior for String -> Bool

- Source/SwiftyJSON.swift
Expression implicitly coerced from 'String?' to Any
> Fix warning In XCode 8.1 (8B62)

- SwiftyJSON.xcodeproj/project.pbxproj
This PR explicitly set the Provisioning Style to Automatic in the iOS, tvOS, and watchOS target.
This has been done by simply unchecking and checking again the checkbox on the General tab.
Having the style explicitly set in the project file can help with scripts.
I didn't open an issue to suggest this change because it's super easy to implement anyway. If you don't find it valuable feel free to close the PR  ¯_(ツ)_/¯.
I didn't touch the macOS one because it was set to manual, and I thought there might have been a reason for that. If that's not the case I'm happy to update with macOS as well.
Cheers
> Explicit Provisioning Style Automatic

- Source/SwiftyJSON.swift
- Tests/SwiftyJSONTests/NumberTests.swift
The `isBool` function on the NSNumber extension uses `trueObjCType`, which represents the type encoding for `true` represented as an NSNumber, and `falseObjCType`, which represents the type encoding for `false` represented as an NSNumber. Both type encodings are equal to `c`. However, an NSNumber that wraps around a value of type Int8 also has a type encoding of `c`.
Therefore, a user who passes in a value of 0 or 1 (of type Int8) into JSON will expect to see the numbers 0 or 1 as the output because that was the intent. Unfortunately, that value will be wrapped into NSNumber and be considered a bool, so the user will see `true` or `false` instead.
To fix this, when setting a new value of type Int8 on the computed properties `int8` or `int8Value`, the new value should be used to directly …
> Fixes #692 - Need to check for Int8, a special case

- README.md
- Source/SwiftyJSON.swift
- Tests/SwiftyJSONTests/PrintableTests.swift
Swift cannot represent dictionaries with `nil` values as json (http://stackoverflow.com/questions/13908094/how-to-include-null-value-in-the-json-via-nsjsonserialization) and the current SwiftyJSON string representation that relies on the default swift JSON string representation will fail as way.
Here I created a custom string representation that doesn't doesn't rely on the built in one, and can handle things with nil or values. I also added a few tests.
> Represent JSON as string even if Swift can't do it

- .travis.yml
- scripts/ci.sh
Relate to #733. 
It seems like TravisCI does not support `travis_retry` to cooperate with an inner shell script. See this [tweet](https://twitter.com/plexus/status/499194992632811520).
> [CI Build Result](https://travis-ci.org/SwiftyJSON/SwiftyJSON/builds/178321916)
> scripts/ci.sh: line 5: travis_retry: command not found
> scripts/ci.sh: line 7: travis_retry: command not found
> scripts/ci.sh: line 9: travis_retry: command not found
So this PR will move scrips into `.travis.yml` and drop `ci.sh`.
> Fix travis_retry command not found

- Tests/SwiftyJSONTests/RawTests.swift
This PR strengthens the tests around the JSON.rawData() function.
The https://github.com/IBM-Swift/SwiftyJSON fork has problems serializing nested json, it returns nil. 
The SwiftyJSON/SwiftyJSON has no problems serializing nested json. It works as it should.
I have added a unittest that hopefully can cause the problem to be fixed in the IBM-Swift/SwiftyJSON fork.
This was my original proof of concept code for recreating the problem.
func asJson() -> JSON {
let user: JSON = [
"name": "John Doe"
]
return [
"alarmLevel": 123,
"user": user
]
}
func main() {
let json = asJson()
let s = json.rawString() ?? "ERROR"
print(s)
}
Output when using SwiftyJSON/SwiftyJSON
{
"alarmLevel" : 123,
"user" : {
"name" : "John Doe"
}
}
Output when using IBM-Swift/SwiftyJSON
ERROR
> RawTests.testNestedJSON() added

- Example/Playground.playground/Contents.swift
- Source/SwiftyJSON.swift
- Tests/SwiftyJSONTests/BaseTests.swift
- Tests/SwiftyJSONTests/PerformanceTests.swift
- Tests/SwiftyJSONTests/SequenceTypeTests.swift
I do not anticipate your accepting of this pull request because it is a non-backward compatible change, something that you might understandably be reluctant to do in an interim release. But it might be something for you to consider for your next major release.
In my opinion, the error handling in `init(data:options:error:)` is remarkably unswifty. You should not have `NSErrorPointer` parameter, because naive implementations will fail to capture the error correctly (see [this Stack Overflow question](http://stackoverflow.com/a/41421533/1271826)).
Instead, this initializer should just be changed to `throw` errors. This code makes that change.
---
My original release notes are below:
---
The problem is that when users call `let json = JSON(data: data)`, they are not informed of the error, …
> Fix init(data:) error handling:

- Example/Example/AppDelegate.swift
Hello,
I See JSON(data: data) has throws exception, so add 'try' in front, the error "call can throw but is not marked with try" can fixed.
public init(data: Data, options opt: JSONSerialization.ReadingOptions = []) throws {
}
> call can throw but is not marked with try

- README.md
- Source/SwiftyJSON.swift
- Tests/SwiftyJSONTests/BaseTests.swift
- Tests/SwiftyJSONTests/MergeTests.swift
- Tests/SwiftyJSONTests/RawTests.swift
- Tests/SwiftyJSONTests/SubscriptTests.swift
Continues the work of #774 , make SwiftyJSON's error handling moving from NSError to Swift.Error.
This PR introudces a new `SwiftyJSONError` type and deprecated those old NSError types.
Here is the migration guide:
Old 3.X | New 4.X
-----|-----
ErrorDomain | SwiftyJSONError.errorDomain
ErrorUnsupportedType | SwiftyJSONError.unsupportedType
ErrorIndexOutOfBounds | SwiftyJSONError.indexOutOfBounds
ErrorWrongType | SwiftyJSONError.wrongType
ErrorNotExist | SwiftyJSONError.notExist
ErrorInvalidJSON | SwiftyJSONError.invalidJSON
> [4.0.0] Error handling

- Source/SwiftyJSON.swift
According to Swift's documentation, we can make a structure's property getter public, and its property setter private / fileprivate, by combining the public and private(set) / fileprivate(set) access-level modifiers. 
```
public struct ExampleStruct {
public fileprivate(set) vat type: Int = 0
}
```
Thus, what this commit does is that it changes the structure JSON's type and error property declaration in this way, which is a more concise and clearer way compared to the original one.
> Declare JSON’s type and error in a clearer and more concise way.

- Source/SwiftyJSON.swift
The following code will cause a crash. Of course, usually user would not intendedly pass a negative index when accessing a json object of array. However, if the index was calculated by other part of code, it could be negative. What this PR did is just to add the logic of checking index >=0 within subscript(index:) method.
```
var json = JSON(parseJSON: "[1.0, 2.0]")
var index = -1
json[index] = 2.0
```
> Fix a potential crash issue by checking whether index is out of json array’s bound.

- Source/SwiftyJSON.swift
NSNumber's isBool extension is not designated to be accessed as part of SwiftyJSON.
Will fix #812
> Change NSNumber extension’s access modifier to fileprivate

- README.md
Some examples in `README.md` makes warning in `XCode Version 8.3.2 (8E2002)`.
`json['blah'].error` to `json['blah'].error!` in README.
No issues yet about this.
> Update examples that makes warning in README

- Example/Example/AppDelegate.swift
- Example/Example/ViewController.swift
The file names in the license of some files were wrong, probably because of copying the license text and forgetting about the name
> Fixed name in licenses

- Example/Playground.playground/Contents.swift
- Source/SwiftyJSON.swift
- SwiftyJSON.xcodeproj/project.pbxproj
- Tests/SwiftyJSONTests/CodableTests.swift
In some Codable instances, when we analyze a deep nested JSON field, it is very difficult to use. So if `JSON` implements Codable protocol, it can provide a very good solution, for example.
```swift
struct SomeDeepNestedModel: Codable {
let id: Int64
//some variables
//...
private var json: JSON?
var theDeepNestedValue: String? {
return json?["nested1"][1]["nested2"]["value"].string
}
}
```
**Does this have tests?**
Yes - CodableTests.swift
**Does this break the public API?**
No
**Is this a new feature (Requires minor version bump)?**
Yes
**Does this have documentation?**
No
> Support Codable protocol

- .travis.yml
- Source/SwiftyJSON.swift
- SwiftyJSON.podspec
- SwiftyJSON.xcodeproj/project.pbxproj
- Tests/SwiftyJSONTests/DynamicMemberLookupTests.swift
- Tests/SwiftyJSONTests/SubscriptTests.swift
This proposal introduces a new @dynamicMemberLookup attribute. Types that use it provide "dot" syntax for arbitrary names which are resolved at runtime - in a completely type safe way. This provides syntactic sugar that allows the user to write
[introduce-user-defined-dynamic-member-lookup-types](https://github.com/apple/swift-evolution/blob/master/proposals/0195-dynamic-member-lookup.md#introduce-user-defined-dynamic-member-lookup-types)
i've added a subscript function with dynamic member, so users can use dot instead of [],
let name = json.name
//The same as: let name = json["name"]
let phoneNumber = json.user.contactInfo.phoneNumber
//The same as: let name = json["user"]["contactInfo"]["phoneNumber"]
- [yes ] Does this have tests?
- [ yes] Does this have documentation?
- [ no] Does …
> Dynamic Member Lookup introduced in Swift 4.2, now we can use dot, instead of brackets

- Package.swift
- SwiftyJSON.podspec
- SwiftyJSON.xcodeproj/project.pbxproj
Xcode 12 bumps minimum iOS deployment target to iOS 9. Several changes have been made to go along with this:
1. `platforms` removed from Package.swift. Those platforms only specify minimum deployment target, if it is **higher** than minimum SPM deployment target. Thus if they are omitted, Swift Package will automatically support all platforms supported by current tools. 
2. iOS deployment target in CocoaPods bumped to iOS 9
3. iOS deployment target in Xcode project bumped to iOS 9.
> Support Xcode 12

- SwiftyJSON.xcodeproj/project.pbxproj
Xcode 13.3 introduces new build logic. If header step is defined after compilation it can throw errors during incremental builds.
`Cycle inside SwiftyJSON; building could produce unreliable results. This usually can be resolved by moving the target's Headers build phase before Compile Sources.`
> Reorder build phases to fix Xcode 13.3 issue

- SwiftyJSON.xcodeproj/project.pbxproj
**Summary of Changes**
This PR improves the building process of the framework using xcodebuild by including PrivacyInfo.xcprivacy in the resulting artifact. This fixes an oversight and ensures consistency across different build systems.
**Changes Made**
Updated File: Only the xcodeproj file was changed. This update ensures that PrivacyInfo.xcprivacy is included when the framework is built using xcodebuild.
**Context and Related Issues**
This PR addresses an issue from a previous PR (https://github.com/SwiftyJSON/SwiftyJSON/pull/1150), which added PrivacyInfo.xcprivacy to the Package.swift and SwiftyJSON.podspec files but failed to update the xcodeproj file accordingly. Because of this oversight, artifacts built with xcodebuild did not include PrivacyInfo.xcprivacy.
Checklist - While not …
> Fix missing PrivacyInfo.xcprivacy in xcodeproj file

- README.md
URL is outdated and leads to spammy/phishy site through redirects.
> Remove spam URL

- .swiftlint.yml
- A SwiftLint rule was updated to use its new name. This is a refactor and does not affect the runtime behavior.
- Only `swiftlint.yml` was updated.
- Resolve a SwiftLint warning when running `swiftlint` on a project build that uses this dependency
- n/a
- n/a
- no
- This is not a functional change. I will leave it up to the maintainers to decide if it really needs to be released by itself. But I think there should not be any issues as long as …
> Update rule in .swiftlint.yml to resolve a warning
