SwiftyJSON/SwiftyJSON

README.md
Shouldn't the username type should be NSString?
=> Fix README.md nested example

README.md
The new Cocoapods 36 is ready.
=> Update README for new Cocoapods

SwiftyJSON.xcodeproj/project.pbxproj
Make life a little easier for those don't have distribution certs set up, carthage will handle signing anyways
https://github.com/Carthage/Carthage/issues/281#issuecomment-70126876
=> Better support for carthage users

README.md, Source/SwiftyJSON.swift
(array does not expose a setter...)
=> [README.md] Setter for JSON array should use arrayObject not array 

SwiftyJSON.xcodeproj/xcshareddata/xcschemes/SwiftyJSON OSX.xcscheme, SwiftyJSON.xcodeproj/xcshareddata/xcschemes/SwiftyJSON iOS.xcscheme
Currently tests are being built when compiling the scheme. Tests should only be built for testing.
=> Only building tests for testing

README.md
It wasn' t clear what to import in the doc.
=> add instruction on import to README

Source/SwiftyJSON.swift
It's similar with problem in #143
=> Allow construction of JSON from [String: JSON]

Source/SwiftyJSON.swift
Related: https://github.com/SwiftyJSON/SwiftyJSON/issues/259
=> Fix NPE on init

Info-watchOS.plist, SwiftyJSON.xcodeproj/project.pbxproj, SwiftyJSON.xcodeproj/xcshareddata/xcschemes/SwiftyJSON watchOS.xcscheme
Since #257 seems to bit dead and has a wrong `PRODUCT_BUNDLE_IDENTIFIER` I created a new fork mainly for using it myself…
=> watchOS target

README.md, Source/SwiftyJSON.swift, Tests/BaseTests.swift
Sometimes it's important to know whether value listed in JSON or not.
=> Existence check

README.md
=> println -> print in README.md

SwiftyJSON.podspec
Just one line to make tvOS play nice via cocoapods :)
=> Added tvOS deployment target to podspec

Example/Example.xcodeproj/project.pbxproj, Example/Playground.playground/Contents.swift, Example/Playground.playground/contents.xcplayground, Example/Playground.playground/timeline.xctimeline
=> Add Playground File

README.md
=> fixed Alamofire & SwiftJSON integration example

Source/SwiftyJSON.swift
This pull request makes the library potentially safer by removing almost all instances of force unwrapping in favor of optional binding and nil coalescing.
Please take a look and let me know what you think. I've run the tests to verify this functionality, and all seems good there.
=> Reduces Force Unwrapping with Optional Binding and Nil Coalescing

Source/SwiftyJSON.swift
=> Use minimumCapacity Parameter to Optimize Dictionary Creation

.travis.yml, Source/SwiftyJSON.swift, SwiftyJSON.xcodeproj/project.pbxproj, Tests/RawTests.swift, Tests/SequenceTypeTests.swift
=> Valid Swift 3.0 code

README.md
Hi,
Thanks for your awesome repo. I added "Getting an array of string from a JSON Array" to subscript section.
I hope that will help others.
Good luck.
=> Add Getting an array of string from a JSON Array

Package.swift
Manifest file should not be empty in Swift 3.0
=> filled Manifest

README.md
=> Fix configuration to write in Cartfile

Source/SwiftyJSON.swift
Added little more descriptive comment. This one is the follow up to the PR that was 4 months old and i had to close it because it had redundant commits.
=> Typos in Comments correction

Source/SwiftyJSON.swift
=> Fix infinite loop with JSON.null

README.md
Adds an example to the read me with an example of nested json objects.
=> update readme with nested example

Source/SwiftyJSON.swift, SwiftyJSON.xcodeproj/project.pbxproj, Tests/NestedJSONTests.swift, Tests/PerformanceTests.swift
Currently, getting rawdata from JSON objects fails and breaks when nesting other JSON objects together. This PR fixes that and adds tests for the test cases where this can fail.
=> Adds Support for Nested JSON

README.md
Fixed wrong markdown syntax as spaces, line break and so on.
=> Fix wrong markdown syntax in README.md

README.md
=> Fix markdown syntax.

Example/Playground.playground/Contents.swift, Example/Playground.playground/contents.xcplayground
Finish subscript part.
Add descriptions.
=> [playground] Finish subscript part

README.md, Source/SwiftyJSON.swift
=> Fix 'AnyObject' in comment and README.md

Source/SwiftyJSON.swift, Tests/SwiftyJSONTests/NumberTests.swift, Tests/SwiftyJSONTests/RawTests.swift, Tests/SwiftyJSONTests/StringTests.swift
@zhigang1992 Please review
Fixes https://github.com/SwiftyJSON/SwiftyJSON/issues/703
Pretty straightforward, let me know if you have any question
=> Fix all Xcode 8.1 compilation warnings

scripts/ci.sh
Update script to get rid of CI fails randomly for pending PR.
=> [CI] Update scripts

Source/SwiftyJSON.swift, Tests/SwiftyJSONTests/BaseTests.swift, Tests/SwiftyJSONTests/StringTests.swift
=> Turn JSON.URL into lower-cased JSON.url

Example/Example.xcodeproj/project.pbxproj, Source/SwiftyJSON.swift, SwiftyJSON.xcodeproj/project.pbxproj, SwiftyJSON.xcodeproj/xcshareddata/xcschemes/SwiftyJSON OSX.xcscheme, SwiftyJSON.xcodeproj/xcshareddata/xcschemes/SwiftyJSON iOS.xcscheme, SwiftyJSON.xcodeproj/xcshareddata/xcschemes/SwiftyJSON tvOS.xcscheme, SwiftyJSON.xcodeproj/xcshareddata/xcschemes/SwiftyJSON watchOS.xcscheme, Tests/SwiftyJSONTests/PrintableTests.swift
=> Swift 3.0.2 compatible

Source/SwiftyJSON.h, Source/SwiftyJSON.swift, Tests/SwiftyJSONTests/ArrayTests.swift, Tests/SwiftyJSONTests/BaseTests.swift, Tests/SwiftyJSONTests/ComparableTests.swift, Tests/SwiftyJSONTests/DictionaryTests.swift, Tests/SwiftyJSONTests/LiteralConvertibleTests.swift, Tests/SwiftyJSONTests/NumberTests.swift, Tests/SwiftyJSONTests/PerformanceTests.swift, Tests/SwiftyJSONTests/PrintableTests.swift, Tests/SwiftyJSONTests/RawRepresentableTests.swift, Tests/SwiftyJSONTests/RawTests.swift, Tests/SwiftyJSONTests/SequenceTypeTests.swift, Tests/SwiftyJSONTests/StringTests.swift, Tests/SwiftyJSONTests/SubscriptTests.swift
This is a legit and very important PR. Hope you like it 😃
=> Hello 2017

SwiftyJSON.xcodeproj/project.pbxproj
=> [Optimization] Update LLVM and Swift compiler level

SwiftyJSON.xcodeproj/project.pbxproj, Tests/SwiftyJSONTests/MutabilityTests.swift
As an improvement for #793, fix #215 and #800
=> [Tests] Improve Mutability test cases

Example/Example/ViewController.swift
=> Add a title of NavigationBar with type on Example

ISSUE_TEMPLATE, PULL_REQUEST_TEMPLATE
=> Add github ISSUE and PULL_REQUEST TEMPLATE

.swiftlint.yml, Example/Example/AppDelegate.swift, Example/Example/ViewController.swift, Example/Playground.playground/Contents.swift, Source/SwiftyJSON.swift, SwiftyJSON.xcodeproj/project.pbxproj, Tests/SwiftyJSONTests/ArrayTests.swift, Tests/SwiftyJSONTests/BaseTests.swift, Tests/SwiftyJSONTests/ComparableTests.swift, Tests/SwiftyJSONTests/DictionaryTests.swift, Tests/SwiftyJSONTests/LiteralConvertibleTests.swift, Tests/SwiftyJSONTests/MergeTests.swift, Tests/SwiftyJSONTests/NestedJSONTests.swift, Tests/SwiftyJSONTests/NumberTests.swift, Tests/SwiftyJSONTests/PerformanceTests.swift, Tests/SwiftyJSONTests/PrintableTests.swift, Tests/SwiftyJSONTests/RawRepresentableTests.swift, Tests/SwiftyJSONTests/RawTests.swift, Tests/SwiftyJSONTests/SequenceTypeTests.swift, Tests/SwiftyJSONTests/StringTests.swift, Tests/SwiftyJSONTests/SubscriptTests.swift
=> [SwiftLint] SwiftLint compatible 

Example/Example/ViewController.swift, Source/SwiftyJSON.swift, Tests/SwiftyJSONTests/MutabilityTests.swift, Tests/SwiftyJSONTests/NestedJSONTests.swift
=> [SwiftLint] Corrected Trailing Whitespace

Source/SwiftyJSON.swift
Hi!
I found a small spelling mistake in the docs. Thought I'd fix it 😊
=> Fix spelling mistake in SwiftyJSON.swift

Source/SwiftyJSON.swift, Tests/SwiftyJSONTests/BaseTests.swift, Tests/SwiftyJSONTests/RawRepresentableTests.swift
=> [SwiftLint] Prefer `!= nil` over `let _`

Example/Playground.playground/Contents.swift, Source/SwiftyJSON.swift, Tests/SwiftyJSONTests/BaseTests.swift, Tests/SwiftyJSONTests/PerformanceTests.swift, Tests/SwiftyJSONTests/SequenceTypeTests.swift
=> Error handling

Tests/SwiftyJSONTests/MutabilityTests.swift
Improved testcases of removability of Array and Dictionary
Close #870
=> Address #870

Source/SwiftyJSON.swift
Fix wrong descriptions and renamed in deprecated error code
No relation
No relation
- [] Does this have tests?
- [] Does this have documentation?
- [] Does this break the public API (Requires major version bump)?
- [] Is this a new feature (Requires minor version bump)?
No relation
=> Fix wrong descriptions and renamed in deprecated error code

Source/SwiftyJSON.swift, Tests/SwiftyJSONTests/SubscriptTests.swift
=> Add "yes" and "1" to string.boolValue array

Tests/SwiftyJSONTests/MergeTests.swift, Tests/SwiftyJSONTests/MutabilityTests.swift, Tests/SwiftyJSONTests/NumberTests.swift, Tests/SwiftyJSONTests/RawTests.swift
=> Address #892

SwiftyJSON.xcodeproj/project.pbxproj
=> Fix broken path after renaming

Example/Playground.playground/Contents.swift
I completed the live docs using playground according to the latest version. 
Update the playground documentation
Add sections of usage from README
- [v] Does this have tests?
- [v] Does this have documentation?
- [] Does this break the public API (Requires major version bump)? no problem
- [] Is this a new feature (Requires minor version bump)? no problem
=> Update the playground documentation

README.md
1. Delete a depreacted example: NilLiteral and update comments to fit the style
2. Fix outdated examples of Raw object section in README
`README.md`
No need
No need
No
No
=> Update deprecated examples and comments to fit the style

README.md
Example in README doesn't compile
=> Update README to specify correct JSONSubscriptType

README.md
=> Updated broken Twitter API link

.travis.yml
This morning the Xcode 9.3 image is just out.
https://github.com/travis-ci/travis-ci/issues/9416
=> Update osx image to 9.3

Source/SwiftyJSON/SwiftyJSON.swift, Tests/SwiftJSONTests/RawRepresentableTests.swift
=> fix compile warning, which will be compile error in upcoming swift 6

README.md
Fixed errors in README.MD
Issue #1144
let json = JSON(data: dataFromNetworking) should be for example let json = try? JSON(data: dataFromNetworking)
=> Errors in readme #1144

.travis.yml
https://app.travis-ci.com/github/SwiftyJSON
=> Delete .travis.yml -- Travis CI is no longer free to open source

README.md
Updates readme with info on removing dictionary keys in place
=> Add info on removing dictionary keys in place
